services:
  master:
    image: ubuntu:22.04
    container_name: kube-lab-master
    privileged: true
    ports:
      - "${LAB_PORT}:80"
    env_file:
      - lab.env
    networks:
      - labnet
    volumes:
      - nginx_config:/etc/nginx
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y curl wget docker.io nodejs npm git build-essential python3 openjdk-11-jdk nginx &&
        
        # Start internal services
        docker run -d -p 9000:9000 --name portainer portainer/portainer-ce &&
        docker run -d -p 3001:3000 --name grafana grafana/grafana &&
        docker run -d -p 8200:8200 --name vault -e VAULT_DEV_ROOT_TOKEN_ID=root -e VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200 hashicorp/vault &&
        docker run -d -p 8082:80 --name gitlab gitlab/gitlab-ce:latest &&
        docker run -d -p 9090:9090 --name prometheus prom/prometheus &&
        docker run -d -p 9100:9100 --name node-exporter quay.io/prometheus/node-exporter:latest &&
        docker run -d -p 8888:8888 -v /var/run/docker.sock:/var/run/docker.sock --name dozzle amir20/dozzle &&

        # Inline NGINX config
        echo 'events {}' > /etc/nginx/nginx.conf &&
        echo 'http {' >> /etc/nginx/nginx.conf &&
        echo '  server {' >> /etc/nginx/nginx.conf &&
        echo '    listen 80;' >> /etc/nginx/nginx.conf &&
        echo '    location /portainer/ { proxy_pass http://localhost:9000/; }' >> /etc/nginx/nginx.conf &&
        echo '    location /grafana/ { proxy_pass http://localhost:3001/; }' >> /etc/nginx/nginx.conf &&
        echo '    location /vault/ { proxy_pass http://localhost:8200/; }' >> /etc/nginx/nginx.conf &&
        echo '    location /gitlab/ { proxy_pass http://localhost:8082/; }' >> /etc/nginx/nginx.conf &&
        echo '    location /prometheus/ { proxy_pass http://localhost:9090/; }' >> /etc/nginx/nginx.conf &&
        echo '    location /node-exporter/ { proxy_pass http://localhost:9100/; }' >> /etc/nginx/nginx.conf &&
        echo '    location /dozzle/ { proxy_pass http://localhost:8888/; }' >> /etc/nginx/nginx.conf &&
        echo '  }' >> /etc/nginx/nginx.conf &&
        echo '}' >> /etc/nginx/nginx.conf &&

        nginx -g 'daemon off;'
      "

volumes:
  nginx_config:

networks:
  labnet:
    driver: bridge