services:
  master:
    image: ubuntu:22.04
    container_name: kube-lab-master
    privileged: true
    ports:
      - "6443:6443"     # Kubernetes API
      - "8001:8001"     # Kubernetes Dashboard
      - "9000:9000"     # Portainer
      - "5000:5000"     # Local Registry
      - "8080:8080"     # Helm Dashboard
      - "8081:8081"     # YAML Editor
      - "8443:8443"     # Code IDE
      - "8888:8888"     # Dozzle Logs
      - "3000:3000"     # Welcome Page
      - "9091:9091"     # Kubebox Terminal
      - "8082:8082"     # GitLab CI/CD
      - "8200:8200"     # Vault GUI
    networks:
      - labnet
    volumes:
      - portainer_data:/data
      - kubeconfig:/root/.kube
      - gitlab_data:/var/opt/gitlab
      - vault_data:/vault/file
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y curl wget docker.io nodejs npm git build-essential python3 openjdk-11-jdk nginx unzip &&
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--disable traefik --disable servicelb --docker' sh - &&
        mkdir -p /root/.kube &&
        cp /etc/rancher/k3s/k3s.yaml /root/.kube/config &&
        sed -i 's/127.0.0.1/localhost/' /root/.kube/config &&
        docker run -d -p 5000:5000 --name local-registry registry:2 &&
        docker run -d -p 9000:9000 -v portainer_data:/data --name portainer portainer/portainer-ce &&
        docker run -d -p 8888:8888 -v /var/run/docker.sock:/var/run/docker.sock --name dozzle amir20/dozzle &&
        git clone https://github.com/komodorio/helm-dashboard.git /helm-dashboard &&
        cd /helm-dashboard && npm install && npm run build && npm start &
        git clone https://github.com/guifier/yaml-editor.git /yaml-editor &&
        cd /yaml-editor && npm install && npm start -- --port 8081 &
        curl -fsSL https://code-server.dev/install.sh | sh &&
        code-server --bind-addr 0.0.0.0:8443 --auth none &
        git clone https://github.com/astefanutti/kubebox.git /kubebox &&
        cd /kubebox && npm install && PORT=9091 npm start &
        docker run -d --name gitlab -p 8082:80 -v gitlab_data:/var/opt/gitlab \
          -e GITLAB_OMNIBUS_CONFIG=\"external_url 'http://localhost:8082'; gitlab_rails['registry_enabled'] = true;\" \
          gitlab/gitlab-ce:latest &&
        docker run -d --name vault -p 8200:8200 -e VAULT_DEV_ROOT_TOKEN_ID=root -e VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200 \
          -v vault_data:/vault/file hashicorp/vault:latest &&
        echo '
        apiVersion: v1
        kind: Namespace
        metadata:
          name: kubernetes-dashboard
        ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: kubernetes-dashboard
          namespace: kubernetes-dashboard
        spec:
          replicas: 1
          selector:
            matchLabels:
              k8s-app: kubernetes-dashboard
          template:
            metadata:
              labels:
                k8s-app: kubernetes-dashboard
            spec:
              containers:
              - name: kubernetes-dashboard
                image: kubernetesui/dashboard:v2.7.0
                ports:
                - containerPort: 8443
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: kubernetes-dashboard
          namespace: kubernetes-dashboard
        spec:
          ports:
          - port: 443
            targetPort: 8443
          selector:
            k8s-app: kubernetes-dashboard
        ' > /dashboard.yaml &&
        kubectl apply -f /dashboard.yaml &&
        kubectl proxy --address=0.0.0.0 --port=8001 --accept-hosts='^localhost$' &
        echo '
        <html>
        <head><title>Welcome to Kubernetes Lab</title></head>
        <body style=\"font-family:sans-serif;\">
        <h1>Kubernetes Lab Ready</h1>
        <ul>
          <li><a href=\"http://localhost:9000\">Portainer GUI</a></li>
          <li><a href=\"http://localhost:8001\">Kubernetes Dashboard</a></li>
          <li><a href=\"http://localhost:8080\">Helm Dashboard</a></li>
          <li><a href=\"http://localhost:8081\">YAML Editor</a></li>
          <li><a href=\"https://localhost:8443\">Code IDE (with Git)</a></li>
          <li><a href=\"http://localhost:8888\">Log Viewer (Dozzle)</a></li>
          <li><a href=\"http://localhost:9091\">Kubebox Terminal</a></li>
          <li><a href=\"http://localhost:8082\">GitLab CI/CD</a></li>
          <li><a href=\"http://localhost:8200\">Vault Secrets Manager</a></li>
          <li><a href=\"http://localhost:5000\">Local Registry</a></li>
        </ul>
        </body>
        </html>
        ' > /var/www/html/index.html &&
        echo 'server { listen 3000; root /var/www/html; index index.html; }' > /etc/nginx/sites-enabled/default &&
        nginx -g 'daemon off;'
      "

volumes:
  portainer_data:
  kubeconfig:
  gitlab_data:
  vault_data:

networks:
  labnet:
    driver: bridge